/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
    String someMethod() {
        return 'from someMethod'
    }
}
